language: ruby
rvm:
- jruby
- 2.1
- 1.9.3
deploy:
  provider: rubygems
  api_key: 701b3f137a894afa3dca9390da8b3afe
  gem: lookout-statsd
  on:
    repo: lookout/statsd
install:
- gem install bundler
- bundle install --jobs=3 --retry=3
